### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by benjaminbrassart** [benjaminbrassart/transcendence#245]
# Checklist

This checklist contains all the criteria that will be verified during the evaluation.

### Preliminary tests

- [x] Ensure the docker compose file is at the root of the repository
- [x] Run the `docker-compose up --build` command

Since the rating is more flexible, do not stop the evaluation process unless you encounter a 500 error, a crash, or anything that actually doesn't work withing the project scope

### Backend

- [x] The backend must be developed using the NestJS framwork
- [x] The database must be a PostgreSQL database
- [ ] During the whole evaluation process, there must be no unhandled warning or error

### Frontend

- [x] The frontend must be done using a TypeScript framework
- [x] Any TypeScript or JavaScript library is allowed
- [ ] During the whole evaluation process, there must be no unhandled warning or error

### Basic checks

- [x] The website is available at the address chosen by the students
- [x] The user can login using the 42 intranet OAuth features
- [x] When logged for the first time, the user is prompted to add information to their account (display name, nickname, avatar and so forth)
- [x] If not logged, the user has access to only little to no information and is prompted to sign in
- [x] The website is a Single Page Application. The user can use the back and forward buttons of the web browser
- [x] You can browse the website using the latest version of Chrome, Firefox or Safari without encountering any problems or errors

### Security concerns

- [ ] Ensure that the website is secured
- [ ] Check the database to verify that passwords are encrypted
- [ ] Check the server-side for validation/sanitation on forms and any user input

If this isn't done, the evaluation ends now

### User profile - private

- [ ] When logged in, the user has access to their profile where they can edit their information. For instance, they can change their nickname (which must be unique) or their avatar (which is a default avatar if not set)

### User profile - public

- [ ] Users can see the profile of other users. A profile contains basic information such as their nickname, their avatar, or a button to add them as friends.
- [ ] Users can block other users. This means they won't receive private messages from the accounts they view, nor their messages in public and private channels.

### Friend interface

- [ ] The user has access to a friends interface, where they can see their friends and their status (offline, online, in a game...)
- [ ] They also have access to basic information about them (name, nickname, avatar...)

### 2FA

- [ ] The user can enable/disable 2FA (two-factory authentication). If enabled, they must pass it in order to sign in. For example, 2FA can use Google Authenticator, a text message, an email...

### Join/leave channels

- [ ] A logged in user can access the website chat service. Join / leaving channels is a manual action. For example, this means it must not be done on logout (the user has to click a `Leave channel` button or something else).
- [ ] The user can join channels (that cam be already created) to have a chat. Some of them can be password-protected. If so, the user has to enter the correct password in order to join the channel.

### Chat usage
- [ ] The users can hat. Messages must be sent/received instantly
- [ ] If the user block another user, the messages from the blocked person must be hidden
- [ ] The user can access the user profile of other players from the chat interface and also invite them for a Pong duel

### Creating channels
- [ ] The user can create new channels
- [ ] The user creator is set as the channel owner and has basic moderation rights (ban/mute users, add a password, set new administrators...)

### Channel roles
- [ ] A user who is an owner of a channel can kick, ban and mute other users and the channels administrators
- [ ] A user who is an administrator of a channel can kick, ban and mute other users, but not the channel owner

### Matchmaking system

- [ ] When logged in, the user has access to a matchmaking system so they can play Pong 1v1 games versus other players on the website
- [ ] When they get matched, a new game is loaded and the two users can start playing

### Gameplay

- [ ] The game itself must be playable and respect the original Pong game
- [ ] The controls must be intuitive or correctly explained (with some rules or manual)
- [ ] When a game is over, either a kind of end-game screen is displayed or the game page just exits

### Spectator mode

- [ ] There is a spectator mode
- [ ] The user can watch any live games
- [ ] They can be accessed through the chat interface or the friends interface
- [ ] There an also be a page dedicated to live games from which the user can access any of them

### Lags and disconnects

- [ ] Unexpected disconnections and lags have to be handled
- [ ] The game and the website must not crash when a user is experiencing lags or is disconnected
- [ ] Handling such issues in an efficient way is appreciated but not mandatory"
  - Pause the game for a defined duration
  - Disconnected users can reconnect
  - Lagging users can catch up to the match
  - etc.
-  [ ] The game must not crash

### Additional features
- [ ] The user can enjoy extra features such as power-ups, different maps, achievements...
